name: Feature Request
description: Suggest a new idea or enhancement for PSLab
title: "[Feature] A brief, descriptive title"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing an idea to make PSLab better! Please take a moment to search existing features and issues to see if this feature has already been requested.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you're requesting.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: What problem does this feature solve?
      description: |
        Explain your use case and the challenge you're facing. More importantly, what is the end-user experience you are trying to achieve that led to the need for this feature?
      placeholder: 'For example: "When I analyze a complex user''s permissions, it''s hard to see X, which makes it difficult to do Y."'
    validations:
      required: true

  - type: textarea
    attributes:
      label: What does the proposed solution look like?
      description: |
        Describe how you imagine this feature working. You can include details about the user interface, workflow, or expected output.
        Mockups or screenshots of a similar feature in another tool are very helpful!
      placeholder: |
        "On the Permissions Analyser page, there should be a new button labeled ''Compare Users''. When clicked, it should..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or supporting information about the feature request here.